name: Pull Request Workflow

on:
  pull_request:
    branches:
      - master

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      # Step 1 - Checkout code
      - uses: actions/checkout@v3

      # Step 2 - Setting up Node.js environment
      - uses: ./.github/workflows/shared

      # Step 3 - Running prettier check
      - name: Run Prettier Check
        run: npm run prettier

      # Step 4 - Running linter
      - name: Run Linter
        run: npm run lint

      # Step 5 - Running tests
      - name: Run Tests
        run: npm test

      # Step 6: Running build (only if everything else succeeds)
      - name: Run Build
        run: npm run build
